### ISSUE TITLE
Task list support

### ISSUE THREAD

**Issue by seadra** [atlassian/commonmark-java#119]
Bullet lists or task lists are listed as  [deployed extensions](https://github.com/commonmark/CommonMark/wiki/Deployed-Extensions#bullet-list) on CommonMark wiki.

This is one of the very useful extensions sorely missing.

**Comment by robinst** [comment]
It would probably be useful to have this, yeah.

I imagine it could be done in an extension that post-processes list items. Not sure how we'd represent it in the document structure yet, maybe just as some kind of attributes on list item nodes.

**Comment by MisterY** [comment]
@robinst, here are some [implementations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+%5B+%5D+to+do%0A-+%5BX%5D+done%0A) from the link @seadra sent. Not sure if it helps but it would be great to have this feature. I'm hoping to replace various tools with just Markdown editors on all the devices.

**Comment by MisterY** [comment]
Thanks for the info. I do not care much about the bureaucracy around it but would really find it useful to have this extension in editors. Most places that implement it, do it in an identical way so the implementation should not have negative consequences.
Quite a few text editors on Android, for example, are utilizing CommonMark Java implementation.

If someone has objections about which extension are used, would it be possible to simply turn them on/off with a preference switch?

**Comment by robinst** [comment]
Let's follow GitHub's spec here: https://github.github.com/gfm/#task-list-items-extension-

It would be in a separate artifact similar to the existing extensions, so it would be optional anyway.

The biggest question I have is how to represent it in the document structure. There's a few options:

* Add an additional custom node, e.g. `TaskListItemMarker`, which is the first element inside a ListItem.
* Add some kind of generic attributes to `ListItem`, e.g. a Map<String, Object>
* Add a subclass of `ListItem` (probably not, it wouldn't be composable with other extensions)

I think I'd prefer the first option so far.

Note this issue is labelled "help wanted", so if someone would like to implement this that would be cool. I'd provide help along the way.

**Comment by dohertyfjatl** [comment]
I have opened a pull request (https://github.com/atlassian/commonmark-java/pull/165) which adds support for task list items as an extension (along the lines of the first option mentioned here https://github.com/atlassian/commonmark-java/issues/119#issuecomment-366390135)

**Comment by robinst** [comment]
The `commonmark-ext-task-list-items` extension has been released in 0.15.0, closing this. We can open more issues for improvements on that.
