### ISSUE TITLE
How create Inline tag / block extension?

### ISSUE THREAD

**Issue by 0xbaadf00d** [atlassian/commonmark-java#123]
Hello,

I would llike implement custom tags but I can't find how to do, cause your DelimiterProcessor only take single char.  Do you have any idea how to implement extension do handle something like this?

    {< youtube youtube-movie-id >}

The purpose is to embed YouTube movie player.

Thanks

**Comment by robinst** [comment]
Hey. You could try using a delimiter processor that uses `{` and `}` and then look at the `Text` nodes in between. If that's not also enclosed in `<>` then just do nothing with the text. Otherwise do whatever you need to do to embed the video.

Another option would be to do it as a post-processing step, basically check all text nodes for a pattern like that and then split the text up into pieces.
