### ISSUE TITLE
Android support with Java 8 source level?

### ISSUE THREAD

**Issue by robinst** [atlassian/commonmark-java#124]
See this comment: https://github.com/atlassian/commonmark-java/issues/30#issuecomment-374672155

@gsantner, how are you consuming the library in your Android project? As far as I know, using it via the built jar should still work.

**Comment by gsantner** [comment]
Getting the lib/jar into the project isn't the problem, neither compiling (where I can overwrite levels to support java 1.8). The problem is on runtime, when java 8 calls do happen, which are simply not available on older JDK's, for example `String.join()`.

Android API 26 / Oreo was the first version of Android that has OpenJDK 8, while >=26 is currently on a very low market share (android stats: 0.8+0.3%) this means that about 99% of android devices/users can't use  this library and that most likely won't change in the near future.

Lower android versions can just make use of some features of Java 8 (e.g. lambdas), but this doesn't add any methods to JDK's classes.

**Comment by noties** [comment]
It is a valid concern, to support Android library should use 1.7 as a language version target. As @gsantner said _something_ can be used (lambdas, method references) as they are backported (_desugared_) by Android Gradle plugin, but runtime is not available for devices below Oreo (26).

My usage is [Markwon](https://github.com/noties/Markwon) an Android library to display markdown _natively_ and I'm using commonmark-java for parsing and traversing parsed nodes.

(_BTW huge thanks for **this** library_)

IMO `commonmark-java` should not be _holded down_ in development by phantom usage on Android. Maybe we could fork the repo and _downgrade_ to 1.7 ...

**Comment by robinst** [comment]
@gsantner or @noties, can you point me to code in commonmark-java that doesn't work on Android because it uses JDK 8 methods/classes?

My plan was to not start using any JDK 8 APIs and thus keep Android support.

So far you haven't provided an actual error/problem, so I'm not sure whether this issue is about a problem right now or about some possible point in the future.

**Comment by gsantner** [comment]
One has to specifically set the application to support java 8, else it won't compile with commonmark. I don't know what/if new/incompatible stuff is used, but I don't want to release a production version which crashes because I want to find it out :D.

I think easiest is if you set to/force java 7 on library side temporary, and see if it compiles or gives some errors.

**Comment by noties** [comment]
@robinst I haven't encountered any problems yet, more thinking about the future. Current latest artifact (`0.11.0`) is in fact compiled with Java 1.7 (checked class files in the jar artifact)

**Comment by robinst** [comment]
It is [targetting Java 7](https://github.com/atlassian/commonmark-java/blob/master/pom.xml#L46-L49), it's just not compiled with a JDK 7 anymore, yeah.

But also, we have tests that run on Android, they parse the whole spec with all the extensions, see here: https://github.com/atlassian/commonmark-java/blob/master/commonmark-android-test/app/src/androidTest/java/com/atlassian/commonmark/android/test/AndroidSupportTest.java

See a passing Android build here: https://travis-ci.org/atlassian/commonmark-java/jobs/344646465

So given that I don't use commonmark-java on Android, I think our story of supporting it anyway is pretty ok. And as stated in the readme, please report it if (by accident) I introduce a problem anyway and I'll fix it.

**Comment by gsantner** [comment]
Great to hear! :D

**Comment by robinst** [comment]
Cool. So I'm gonna close this issue.
