### ISSUE TITLE
Only support some Markdown features?

### ISSUE THREAD

**Issue by nirslsk** [atlassian/commonmark-java#135]
Hi there,

Is there a way to configure commonmark-java to only support some Markdown features? For example at this point in my project I want to have bold/italic formatting and links to begin with, but support other Markdown features when I'm able to render the resulting HTML correctly (I'm rendering to both web and non-web interfaces). Is that doable?

Thanks, Nir

**Comment by robinst** [comment]
Hey! There's support for disabling block-level things such as lists, headings etc, see `enabledBlockTypes` on the parser builder.

For inline syntax it's currently a bit more complicated. But it depends on how you want to render things that you don't support yet: Do you want to show the original markup or do you want to show a text-friendly version of it?

Does that help? Your question is pretty generic, I'd suggest you try it out and see how you go :). In general, because of the AST based approach, it's pretty easy to do some processing before rendering.

**Comment by nirslsk** [comment]
Hey Robin, sorry for the generic question. I did see enabledBlockTypes. The specific problem I ran into was support for images. If a user posts a comment that has an image in it, it'll show fine on the website, but not in the Android app since the control only supports basic HTML. The commonmark-java Image class is a Node though, not a Block, so I couldn't use enabledBlockTypes for it. 

The other thing I considered was just letting commonmark-java parse everything and then remove tags I don't want to support from the resulting HTML. Ideally I'd like to show the original markup, but odds are the user isn't going to try a kind of markup that I don't explicitly support. Do I understand correctly that commonmark-java does not allow for that?

**Comment by robinst** [comment]
What you can do is parse the document, then walk over the nodes with a visitor. If you encounter an Image node, remove it or replace it with a different node, maybe some placeholder. Then render the document. Does that make sense?

**Comment by nirslsk** [comment]
I'll try it out, thanks!

**Comment by robinst** [comment]
No worries, let me know how it goes!
