### ISSUE TITLE
Order of Custom Extension Factories

### ISSUE THREAD

**Issue by chiwanpark** [atlassian/commonmark-java#18]
Hi, I'm creating an extension to parsing YAML style metadata of markdown. Hyphens are generally used to divide metadata section. Following is example:

```markdown
---
key1: value1
key2: value2
---

markdown document start!
```

This format is widely used. We can find lots of example in web.

* https://github.com/apache/flink/blob/master/docs/setup/cluster_setup.md
* https://github.com/apache/incubator-zeppelin/blob/master/docs/docs/interpreter/spark.md
* https://www.npmjs.com/package/meta-marked
* http://pandoc.org/README.html#extension-yaml_metadata_block

But I cannot create the extension to parse metadata because core factories precede the custom extension factories. In above example, `---` is considered as horizontal line by `HorizontalRuleParser`.

I think that the custom extension factories should precede the core factories. It would be helpful to extend parser.

**Comment by robinst** [comment]
My original thinking was that core factories should have precedence because an extension should not be able to change how existing (core) syntax is rendered. But that turns out to be an incomplete thought anyway, because there's tons of ways extensions can do that already.

So, I think I now agree with you that it would make more sense to have the extension factories come first. After all, if you use an extensions, you already have to trust that it does the right thing.

**Comment by robinst** [comment]
Changed now, will be in the next release.

Are you interested in contributing this extension as part of this repository? Seems like something that could be useful to have as part of the "official" extensions.

Anyway, let me know if you hit any other problems or if the API could be improved, until now I've been the only user of the extension API :).

**Comment by chiwanpark** [comment]
Thanks for fast reply.

I'm interested in contributing the metadata extension. Currently, the extension is implemented using Scala. After ported to Java, I'll send a pull request.

**Comment by robinst** [comment]
:+1: looking forward to it!
