### ISSUE TITLE
Escape Raw HTML does not work.

### ISSUE THREAD

**Issue by Israyil** [atlassian/commonmark-java#76]
I have tried to render some text including raw html inside. Whatever I give in escapeHtm() true or false it doesn't work. the given text renders like below:

< test >  |&|  < /test >

&lt;test&gt  |&amp|  &lt/test&gt

There can be a bug in the detection part. correct me if i am doing something wrong.

**Comment by robinst** [comment]
Hey! I'm not sure what you mean, the example is not clear to me. Can you please create a gist instead, and clearly label what the input, the expected output and the actual output is?

But I'm suspecting it's caused by the distinction between HTML blocks and inline elements in CommonMark. Try out the reference implementation here: http://spec.commonmark.org/dingus/?text=%3C%20test%20%3E%20%7C%26%7C%20%3C%20%2Ftest%20%3E

**Comment by Israyil** [comment]
The problem is that I want the renderer to leave characters like <, >, & alone in the text because the browser does not show them when they are turned into &amp, &lt or &gt.

**Comment by robinst** [comment]
> because the browser does not show them when they are turned into &amp, &lt or &gt.

What do you mean by this? If your HTML contains `&lt;`, then it will be shown as `<` in your browser.

**Comment by Israyil** [comment]
Yes, I get it, but it doesn't do that and all I get is &lt, &gt and &amp inside the text. I get the character that I want only if I change it in the debug window into  <, >, &.

**Comment by Israyil** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/3901313/21257189/fe47ab96-c376-11e6-85f1-de8f1217e3f8.png)

**Comment by Israyil** [comment]
issue solved, It was some rendering problem with GWT. Thanks for the answers.

**Comment by robinst** [comment]
:thumbsup:
