### ISSUE TITLE
Html blocks not wrapped in <p/> when escapeHtml set to true

### ISSUE THREAD

**Issue by evpaassen** [atlassian/commonmark-java#78]
I'm using the Parser/HtmlRenderer combo with `escapeHtml(true)`, but this leaves html blocks without being wrapped in a paragraph tag. Please see the following example. It seems like incorrect behaviour to me.

# Parsing code
```java
public String render(String text) {
    Parser parser = Parser.builder().build();
    HtmlRenderer renderer = HtmlRenderer.builder().escapeHtml(true).build();
    Node document = parser.parse(text);
    return renderer.render(document);
}
```

# Input
```markdown
This is a paragraph.

This is a paragraph.

<div>html here</div>

This is a paragraph.

This is a paragraph.

<strong>html here</strong>

This is a paragraph.

This is a paragraph.

<p>html here</p>

This is a paragraph.
```

# Expected output
```html
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
<p>&lt;div&gt;html here&lt;/div&gt;</p>
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
<p>&lt;strong&gt;html here&lt;/strong&gt;</p>
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
<p>&lt;p&gt;html here&lt;/p&gt;</p>
<p>This is a paragraph.</p>
```

# Actual output
```html
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
&lt;div&gt;html here&lt;/div&gt;
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
<p>&lt;strong&gt;html here&lt;/strong&gt;</p>
<p>This is a paragraph.</p>
<p>This is a paragraph.</p>
&lt;p&gt;html here&lt;/p&gt;
<p>This is a paragraph.</p>
```

Note that the line `<strong>html here</strong>` actually is wrapped, but the other two aren't.

**Comment by robinst** [comment]
This is a good point, thanks for raising this issue.

There is an explanation for why `<strong>` gets wrapped in a `<p>`, it's because `<strong>...</strong>` is what's called [raw HTML in the spec](http://spec.commonmark.org/0.27/#raw-html) or inline HTML, which is something that can be a part of a paragraph. To make this more obvious, you can also add some text before or after the `strong` element.

The `<div>` however is a [HTML block](http://spec.commonmark.org/0.27/#html-blocks).

I think it makes sense to wrap escaped HTML blocks in a paragraph. I'll implement that in the next couple of days unless someone speaks up about it :). Or if you'd like to have a stab at it yourself, the code to change would be in the `CoreHtmlNodeRenderer`.

**Comment by robinst** [comment]
Just pushed a commit to implement this. It will be in the next release.
