### ISSUE TITLE
Unexpected success in commonmark-android-test with android-10

### ISSUE THREAD

**Issue by olafdietsche** [atlassian/commonmark-java#81]
In commit 4cfc2e03f49dc0ce2d11695462357fe54afa799f, I changed

```
diff --git a/commonmark-android-test/app/build.gradle b/commonmark-android-test/app/build.gradle
index 3ca56fb..5d940d1 100644
--- a/commonmark-android-test/app/build.gradle
+++ b/commonmark-android-test/app/build.gradle
@@ -10,13 +10,13 @@ if (testPropertiesFile.canRead()) {
 }
 
 android {
-    compileSdkVersion 16
-    buildToolsVersion "21.1.1"
+    compileSdkVersion 10
+    buildToolsVersion "21.1.2"
 
     defaultConfig {
         applicationId "com.atlassian.commonmark.android.test"
-        minSdkVersion 16
-        targetSdkVersion 16
+        minSdkVersion 10
+        targetSdkVersion 10
         versionCode 1
         versionName "1.0"
```
Even though I would expect it to fail, gradle reports 

>...  
>:app:packageSnapshotDebugAndroidTest  
>:app:assembleSnapshotDebugAndroidTest  
>:app:connectedSnapshotDebugAndroidTest  
>BUILD SUCCESSFUL  
>Total time: 1 mins 12.542 secs  

and the report contains 

```
<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="com.atlassian.commonmark.android.test.AndroidSupportTest" tests="8" failures="0" errors="0" skipped="0" time="50.773" timestamp="2017-03-02T17:26:42" hostname="localhost">
  <properties>
    <property name="device" value="android-10(AVD) - 2.3.3" />
    <property name="flavor" value="SNAPSHOT" />
    <property name="project" value="app" />
  </properties>
  <testcase name="parseTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.03" />
  <testcase name="headingAnchorExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="7.379" />
  <testcase name="insExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.549" />
  <testcase name="strikethroughExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.069" />
  <testcase name="autolinkExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.423" />
  <testcase name="tablesExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.019" />
  <testcase name="yamlFrontMatterExtensionTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.07" />
  <testcase name="htmlRendererTest" classname="com.atlassian.commonmark.android.test.AndroidSupportTest" time="6.059" />
</testsuite>
```

When I copy commonmark-core into a test project (android-10) and build it as part of this project, the build fails as expected.

**Comment by robinst** [comment]
I'm not up to speed with how Android builds work. Can you explain what the issue is in more details? Is the way we test on Android not testing the right things?

Maybe @JinneeJ would be able to help with this.

**Comment by olafdietsche** [comment]
Actually, I don't know either, at least when it comes to gradle and commonmark.

I slightly modified commonmark, so it works with a small project for Android 2.3.6 (android-10). I can build it within my project with ant, and it works fine so far.

In order to return my changes, I wanted to verify with the existing tests, and stumbled upon the unexpected result. I get a success with or without my changes, even though the emulator is running android-10.

This is why I reported this issue. To dig deeper and understand how the tests work will take some time however.

**Comment by robinst** [comment]
Hm, ok. So what's the failure when you build it as part of your project?

**Comment by JinneeJ** [comment]
Initially there were changes in commonmark to support Android sdk 15 at least. There is sdk version 16 in tests because CI doesn't have emulator with sdk 15 (afaik).

It's likely that commonmark might work on android sdk 10 now. As far as I remember Java in Android SDK didn't change in span of SDK 10-15. 

+1 to question what exactly failed on Android sdk 10 after copying commonmark core.

**Comment by olafdietsche** [comment]
It does work on android-10, with a very small change. In commonmark/src/main/java/org/commonmark/internal/util/Html5Entities.java, I replaced "try with resources" with "try finally"

```
--- a/commonmark/src/main/java/org/commonmark/internal/util/Html5Entities.java
+++ b/commonmark/src/main/java/org/commonmark/internal/util/Html5Entities.java
@@ -45,20 +45,29 @@ public class Html5Entities {
         Map<String, String> entities = new HashMap<>();
         InputStream stream = Html5Entities.class.getResourceAsStream(ENTITY_PATH);
         Charset charset = Charset.forName("UTF-8");
-        try (BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(stream, charset))) {
+        try {
+            BufferedReader bufferedReader = null;
+            try {
+                bufferedReader = new BufferedReader(new InputStreamReader(stream, charset));
                 String line;
                 while ((line = bufferedReader.readLine()) != null) {
                     if (line.length() == 0) {
                         continue;
                     }
+
                     int equal = line.indexOf("=");
                     String key = line.substring(0, equal);
                     String value = line.substring(equal + 1);
                     entities.put(key, value);
                 }
+            } finally {
+                if (bufferedReader != null)
+                    bufferedReader.close();
+            }
```

This is needed, because [`AutoCloseable`](https://developer.android.com/reference/java/lang/AutoCloseable.html) was introduced at API level 19, and according to this [Issue 73483](https://code.google.com/p/android/issues/detail?id=73483) is also available at level 15.

I didn't find the time yet, to investigate further into the android test and find out what is tested and how. One reason why it works - I might have done this wrong - could be that the jar is built upfront, independent of the test. When I build the unmodified commonmark-java (core) as part of my project, it is built together with the rest of the source with android-10 of course, and then it fails with 

>    [javac] /path/to/src/org/commonmark/internal/util/Html5Entities.java:48: error: incompatible types: try-with-resources not applicable to variable type
>    [javac]         try (BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(stream, charset))) {
>    [javac]                             ^
>    [javac]     (BufferedReader cannot be converted to AutoCloseable)

**Comment by robinst** [comment]
> One reason why it works - I might have done this wrong - could be that the jar is built upfront, independent of the test

That might be the reason, yeah. That would be good to fix in the Android test.

As for changing the code, I'd prefer not to do changes for an Android version that was released 6 years ago and only has 1% market share, according to this: https://developer.android.com/about/dashboards/index.html#Platform

(I'm already a bit sad about not being able to use Java 8 because of Android.)

**Comment by JinneeJ** [comment]
I don't see an easy way to fix android tests. I agree the problem is that `commonmark-android-test` use compiled commonmark core that contain valid java byte code (that can work also on android 10). I see 2 ways how we can test compilation of commonmark core in android tests to avoid compilation fails:
1) We can convert commonmark-android-test to maven (but I'm not familiar with maven enough for that) 
2) We can make "hacky" source set for gradle project (but it's an ugly hack and I would avoid it)

In general I'm not sure that it's needed to change android tests since commonmark is supposed to be used as already compiled dependency (and that is what android tests check here). Probably it would be nice to mention in readme something like that: "it's only guaranteed that compiled commonmark work on sdk > 15"

**Comment by olafdietsche** [comment]
Well, if it were easy and obvious, I would have fixed it right away. :-)

@robinst 

>... for an Android version that was released 6 years ago and only has 1% market share

I am biased of course, because my phone belongs to these 1% market share. And even when 1% doesn't sound too much, if there are 1 bln Android phones out there, this would still make 10 mln, which isn't too shabby. :-)

Anyway, I will maintain this in a separate branch nevertheless.

@JinneeJ 

>We can convert commonmark-android-test to maven (but I'm not familiar with maven enough for that)

What would we gain by using maven? I don't object, just curious.

>used as already compiled dependency (and that is what android tests check here).

This sounds like the test checks, if the jar file can be copied to the emulator. If this is the case, I would consider the test's name at least misleading. In my case it is even useless, because I cannot verify, if I introduced a bug or not. Which is why I started the test in the first place.

**Comment by JinneeJ** [comment]
> What would we gain by using maven?

Since commonmark core uses maven build system, having maven system in android tests will allow to build commonmark core with android sdk. So it will be possible to verify that building commonmark core doesn’t fail with android sdk.

I agree that probably naming is misleading. In general I’m not sure what should be tested on Android if all java tests are successful in commonmark-core. The only thing that commonmark-android-tests does - verifying that changes in commonmark-core won’t lead to something like ClassNotFound exception and etc on Android 😊

**Comment by robinst** [comment]
> verifying that changes in commonmark-core won’t lead to something like ClassNotFound exception and etc on Android 😊

Yeah, and I think that's useful.

As I said before, I'm not up-to-date with Android development, but wouldn't you also just pull in an already compiled jar as a dependency. If so, and that works on Android, then I'm not sure we need to change anything. @olafdietsche does consuming commonmark via a jar not work for you?
